# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: dnf.spec

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - centos-stream-9-x86_64
  - job: tests
    trigger: pull_request
    identifier: "dnf-tests"
    targets:
      - centos-stream-9-x86_64
    fmf_url: https://github.com/evan-goode/ci-dnf-stack.git
    fmf_ref: evan-goode/bootc
    tmt_plan: "^/plans/integration/bootc-behave-dnf$"
