version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - cp doc/conf.py.in doc/conf.py

sphinx:
  configuration: doc/conf.py

python:
   install:
   - requirements: doc/requirements.txt
