.\" yum-arch - Yellowdog Updater Modified Arch Tool - creates yum archive databases
.TH "yum-arch" "8" "2002 Jun 8" "Seth Vidal" ""
.SH "NAME"
yum\-arch \- Creates yum distribution database
.SH "SYNOPSIS"
\fByum\-arch\fP [options] directory
.PP 
.SH "DESCRIPTION"
\fByum\-arch\fP is run from the distribution site in order to create the
databases in which yum determines remote package availability.

\fIoptions\fP is one of:
.IP "\fB\-d\fP"
check dependencies and conflicts in tree.
.IP "\fB\-v\fP"
make output verbose.
.IP "\fB\-vv\fP"
make output much more verbose.
.IP "\fB\-n\fP"
don't generate headers.
.IP "\fB\-q\fP"
make output more quiet.
.IP "\fB\-c\fP"
check pkgs with gpg and md5 checksums \- cannot be used with \-n.
.IP "\fB\-z\fP"
compress headers using gzip.
.IP "\fB\-l\fP"
pay attention to symlinks (Default is to ignore symlinks).
.br 
.IP "\fBdirectory\fP"
a directory where you want to create the \fIheaders\fP directory.

.SH "FILES"
.nf 
headers/
headers/header.info
.fi 
.PP 
.SH "SEE ALSO"
.I yum (8)

.PP 
.SH "AUTHORS"
.nf 
Seth Vidal <skvidal@phy.duke.edu>
.fi 

.PP 
.SH "BUGS"
Any bugs which are found should be emailed to the mailing list:
yum@dulug.duke.edu
.fi 
