.TH "yum-updatesd" "8" "" "Jeremy Katz" ""
.SH "NAME"
yum-updatesd \- Update notifier daemon
.SH "SYNOPSIS"
\fByum-updatesd\fP
.SH "DESCRIPTION"
.PP 
\fByum-updatesd\fP provides notification of updates which are
available to be applied to your system.  This notification can be done
either via syslog, email or over dbus.  Configuration is done via the
\fByum-updatesd.conf(5) \fR file.  
.PP 
.SH "SEE ALSO"
.nf
.I yum(8)
.I yum-updatesd.conf(5)
http://yum.baseurl.org/
.fi 
