.TH "yum.conf" "5" "" "Seth Vidal" "yum configuration file"
.SH "NAME"
.LP 
\fByum.conf\fR \- Configuration file for \fByum(8)\fR.
.SH "DESCRIPTION"
.LP 
Yum uses uses a configuration file called
\fByum.conf\fR. This configuration file is searched for
in the following places:
.LP 
/etc/yum.conf
.LP 
.SH "PARAMETERS"
.LP 
There are two types of sections in the yum.conf file: main and server. Main defines all the global configuration options. The server section(s) define the entries for each server.
.SH "[main] options"
.LP 
The [main] section must exist for yum to do anything. It consists of the following options:

.IP \fBcachedir\fR
directory where yum should store its cache and db files.

.IP \fBdebuglevel\fR
debug level. valid numbers are 0\-10.
default is 2.

.IP \fBerrorlevel\fR
debug level. valid numbers are 0\-2.
default is 2.

.IP \fBlogfile\fR
full directory and file name for where yum should write its log file.

.IP \fBassumeyes\fR
1 or 0 - tells yum whether or not to prompt you for confirmation of actions.
Same as -y on the command line. Default to 0.

.IP \fBtolerant\fR
1 or 0 - Tells yum to be tolerant of errors on the command line with regard to 
packages. For example: if you request to install foo, bar and baz and baz is 
installed; yum won't error out complaining that baz is already installed.
same as -t on the command line. Default to 0(not tolerant)

.IP \fBpkgpolicy=\fI[newest|last]\fR
Default: \fInewest\fR.  Package sorting order.  When a package is available from 
multiple servers, \fInewest\fR will install the most recent version of the package 
found. \fIlast\fR will sort the servers alphabetically by \fBserverid\fR and 
install the version of the package found on the last server in the resulting list.
If you don't understand the above then you're best left not including this option at 
all and letting the default occur.

.IP \fBexclude\fR
list of packages to exclude from updates or installs. This should be a space separated list.
Filename globs *,?,., etc are allowed

.IP \fBexactarch\fR
1 or 0 - set to 1 to make yum update only update the architectures of
packages that you have installed. IE: with this enabled yum will not install an i686
package to update an i386 package.

.IP \fBcommands\fR
list of functional commands to run if no functional commands are specified
on the command line. ie: commands  = update foo bar baz quux
none of the short options (-y, -e, -d, etc) will be taken in the field.

.IP \fBdistroverpkg\fR
package to use to determine the "version" of the distribution - can be any
package you have installed - defaults to redhat-release.

.IP \fBdiskspacecheck\fR
set this to 0 to disable the checking for sufficient diskspace before the
rpm transaction is run. default is 1 (to perform the check)

.IP \fBretries\fR
Set the number of times any attempt to retrieve a file should retry before 
returning an error. Setting this to 0 makes it try forever. Default to 3.

.IP \fBkernelpkgnames \fR
list of package names that are kernels - this is really only here for the
kernel updating portion - this should be removed out in 2.1 series.

.IP \fBinstallonlypkgs \fR
list of packages that should only ever be installed, never updated - kernels
in particular fall into this category. Defaults to kernel, kernel-smp,
kernel-bigmem, kernel-enterprise, kernel-debug, kernel-unsupported.

.SH "[server] options"
.LP 
The server section(s) take the following form:
.IP \fBExample\fP:
[serverid] 
.br 
name=Some name for this server
.br 
baseurl=url://path/to/repository/ 
.br 
gpgcheck=[1|0] 
.br 

.IP \fBserverid\fR
must be a unique name for each server, one word.

.IP \fBbaseurl\fR
must be a url to the directory where the yum repository's 'headers' directory lives.
Can be an http://, ftp:// or file:// url.
You can specify multiple urls in one baseurl statement. The best way to do
this is like this:
.br
[serverid]
.br
name=Some name for this server
.br
baseurl=url://server1/path/to/repository/
.br
        url://server2/path/to/repository/
.br
        url://server3/path/to/repository/
.br
If you list more than one baseurl= statement in a repository you will find
yum will ignore the earlier ones and probably act bizarrely. Don't do this,
you've been warned.

.IP \fBname\fR
a human readable string describing the repository.

.IP \fBgpgcheck\fR
either '1' or '0'. This tells yum whether or not it should perform a gpg signature check on the packages gotten from this server

.IP \fBfailovermethod\fR
can be either 'roundrobin' or 'priority'.
roundrobin randomly selects a url out of the list of urls to start with and
proceeds through each of them as it encounters a failure contacting the
host.
.br
priority starts from the first baseurl listed and reads through them
sequentially.
.br
failovermethod defaults to roundrobin if not specified.

.IP \fBexclude\fR
same as the [main] exclude but this is only for this server
variables, listed below, are honored here.

.SH "VARIABLES"
.LP
There are a number of variables you can use to ease maintenance of the
configuration file. They are only useful inside the name, baseurl and
commands fields in the config file.
.LP

.IP \fB$releasever\fR
This will be replaced with the value of the version of the package listed
in \fBdistroverpkg\fR. This defaults to the version of the package
redhat-release

.IP \fB$arch\fR
This will be replaced with your architecture as listed by os.uname()[4] in
pyhton.

.IP \fB$basearch\fR
This will be replaced with your base architecture as they are listed in
archwork.py in yum. For example if your $arch is i686 your $basearch will be
i386.

.IP \fB$YUM0-$YUM9\fR
These will be replaced with the value of the shell environment variable of
the same name. If the shell environment variable does not exist then they
will not be replaced.


.SH "FILES"
.LP 
/etc/yum.conf
.SH "SEE ALSO"
.LP 
yum(8)
