.\" yum - Yellowdog Updater Modified
.TH "yum" "8" ""  "Seth Vidal" ""
.SH "NAME"
yum \- Yellowdog Updater Modified
.SH "SYNOPSIS"
\fByum\fP [options] [command] [package ...]
.SH "DESCRIPTION"
.PP 
\fByum\fP is an interactive, rpm based, package manager. It can automatically
perform system updates, including dependancy analysis and obsolete processing
based on "repository" metadata. It can also perform installation of new
packages, removal of old packages and perform queries on the installed and/or
available packages among many other commands/services (see below)\&. \fByum\fP
is similar to other high level package managers like apt\-get and smart\&.
.PP
While there are some graphical interfaces directly to the \fByum\fP code, more
recent graphical interface development is happening with PackageKit and the
gnome\-packagekit application\&.
.PP 
\fIcommand\fP is one of:
.br 
.I \fR * install package1 [package2] [\&.\&.\&.]
.br 
.I \fR * update [package1] [package2] [\&.\&.\&.]
.br 
.I \fR * check\-update
.br 
.I \fR * upgrade [package1] [package2] [\&.\&.\&.] 
.br
.I \fR * remove | erase package1 [package2] [\&.\&.\&.]
.br 
.I \fR * list [\&.\&.\&.]
.br 
.I \fR * info [\&.\&.\&.]
.br 
.I \fR * provides  | whatprovides feature1 [feature2] [\&.\&.\&.]
.br  
.I \fR * clean [ packages | headers | metadata | dbcache | all ]
.br
.I \fR * makecache
.br
.I \fR * groupinstall group1 [group2] [\&.\&.\&.]
.br
.I \fR * groupupdate group1 [group2] [\&.\&.\&.]
.br 
.I \fR * grouplist [hidden]
.br
.I \fR * groupremove group1 [group2] [\&.\&.\&.]
.br
.I \fR * groupinfo group1 [\&.\&.\&.]
.br
.I \fR * search string1 [string2] [\&.\&.\&.]
.br
.I \fR * shell [filename]
.br
.I \fR * resolvedep dep1 [dep2] [\&.\&.\&.] 
.br
.I \fR * localinstall rpmfile1 [rpmfile2] [\&.\&.\&.] 
.br
.I \fR * localupdate rpmfile1 [rpmfile2] [\&.\&.\&.] 
.br
.I \fR * deplist package1 [package2] [\&.\&.\&.] 
.br
.I \fR * repolist [all|enabled|disabled] 
.br
.I \fR * help [command] 
.br
.PP 
Unless the \-\-help or \-h option is given, one of the above commands
must be present\&.
.PP
Repository configuration is honored in all operations.
.PP 
.IP "\fBinstall\fP"
Is used to install the latest version of a package or
group of packages while ensuring that all dependencies are
satisfied\&.  If no package matches the given package name(s), they are
assumed to be a shell glob and any matches are then installed\&. If the
name starts with an @ character the rest of the name is used as though
passed to the groupinstall command\&.
.IP 
.IP "\fBupdate\fP"
If run without any packages, update will update every currently
installed package.  If one or more packages or package globs are specified, Yum will
only update the listed packages\&.  While updating packages, \fByum\fP
will ensure that all dependencies are satisfied\&. If the packages or globs specified
match to packages which are not currently installed then update will not install them\&.

If the main obsoletes configure option is true (default) or the \-\-obsoletes
flag is present \fByum\fP will include package 
obsoletes in its calculations - this makes it better for distro\-version 
changes, for example: upgrading from somelinux 8.0 to somelinux 9.
.IP 
.IP "\fBcheck\-update\fP"
Implemented so you could know if your machine had any updates that needed to
be applied without running it interactively. Returns exit value of 100 if
there are packages available for an update. Also returns a list of the pkgs
to be updated in list format. Returns 0 if no packages are available for
update. Returns 1 if an error occured.
Running in verbose mode also shows obsoletes.
.IP
.IP "\fBupgrade\fP"
Is the same as the update command with the \-\-obsoletes flag set. See update 
for more details.
.IP 
.IP "\fBremove\fP or \fBerase\fP"
Are used to remove the specified packages from the system
as well as removing any packages which depend on the package being
removed\&.
.IP 
.IP "\fBlist\fP"
Is used to list various information about available
packages; more complete details are available in the \fIList Options\fP
section below\&.
.IP 
.IP "\fBprovides\fP or \fBwhatprovides\fP"
Is used to find out which package provides some feature
or file. Just use a specific name or a file-glob-syntax wildcards to list
the packages available or installed that provide that feature or file\&.
.IP 
.IP "\fBsearch\fP"
Is used to find any packages matching a string in the description, summary
and package name fields of an rpm. Useful for finding a package
you do not know by name but know by some word related to it. 
.IP 
.IP "\fBinfo\fP"
Is used to list a description and summary information about available
packages; takes the same arguments as in the \fIList Options\fP
section below\&.
.IP 
.IP "\fBclean\fP"
Is used to clean up various things which accumulate in the
\fByum\fP cache directory over time.  More complete details can be found in
the \fIClean Options\fP section below\&.
.IP 
.IP "\fBmakecache\fP"
Is used to download and make usable all the metadata for the currently enabled
\fByum\fP repos.
.IP 
.IP "\fBgroupinstall\fP"
Is used to install all of the individual packages in a group, of the specified
types (this works as if you'd taken each of those package names and put them on
the command line for a "yum install" command).
 The group_package_types configuration option specifies which types will
be installed.
.IP 
.IP "\fBgroupupdate\fP"
Is just an alias for groupinstall, which will do the right thing because
"yum install X" and "yum update X" do the same thing, when X is already
installed.
.IP 
.IP "\fBgrouplist\fP"
Is used to list the available groups from all \fByum\fP repos. Groups are marked
as "installed" if all mandatory packages are installed, or if a group doesn't
have any mandatory packages then it is installed if any of the optional or
default package are installed.
The optional "hidden" argument will also list groups marked as not being
"user visible".
.IP 
.IP "\fBgroupremove\fP"
Is used to remove all of the pacakges in a group, unlike "groupinstall" this
will remove everything regardless of group_package_types. It is worth pointing
out that packages can be in more than one group, so "groupinstall X Y" followed
by "groupremove Y" does not do give you the same result as "groupinstall X".
.IP 
.IP "\fBgroupinfo\fP"
Is used to give the description and package list of a group (and which type
those packages are marked as). Note that you can use the yum-filter-data and
yum-list-data plugins to get/use the data the other way around (Ie. what
groups own packages need updating).
.IP 
.IP "\fBshell\fP"
Is used to enter the 'yum shell', when a filename is specified the contents of
that file is executed in yum shell mode. See \fIyum-shell(8)\fP for more info
.IP
.IP "\fBresolvedep\fP"
Is used to list packages providing the specified dependencies, at most one
package is listed per dependency. 
.IP
.IP "\fBlocalinstall\fP"
Is used to install a set of local rpm files. If required the enabled 
repositories will be used to resolve dependencies. 
.IP
.IP "\fBlocalupdate\fP"
Is used to update the system by specifying local rpm files. Only the specified 
rpm files of which an older version is already installed will be installed,
the remaining specified packages will be ignored.
If required the enabled repositories will be used to resolve dependencies.
.IP
.IP "\fBdeplist\fP"
Produces a list of all dependencies and what packages provide those
dependencies for the given packages.
.IP
.IP "\fBrepolist\fP"
Produces a list of configured repositories. The default is to list all
enabled repositories.
.IP
.IP "\fBhelp\fP"
Produces help, either for all commands or if given a command name then the help
for that particular command\&.
.IP
.PP
.SH "GENERAL OPTIONS"
Most command line options can be set using the configuration file as
well and the descriptions indicate the necessary configuration option
to set\&.
.PP 
.IP "\fB\-h, \-\-help\fP"
Help; display a help message and then quit\&.
.IP "\fB\-y\fP"
Assume yes; assume that the answer to any question which would be asked 
is yes\&.
.br
Configuration Option: \fBassumeyes\fP
.IP "\fB\-c [config file]\fP" 
Specifies the config file location - can take http, ftp urls and local file
paths\&.
.br
.IP "\fB\-q, \-\-quiet\fP" 
Run without output.  Note that you likely also want to use \-y\&.
.br
.IP "\fB\-v, \-\-verbose\fP" 
Run with a lot of debugging output\&.
.br
.IP "\fB\-d [number]\fP" 
Sets the debugging level to [number] \- turns up or down the amount of things that are printed\&. Practical range: 0 - 10
.br
Configuration Option: \fBdebuglevel\fP
.IP "\fB\-e [number]\fP" 
Sets the error level to [number] Practical range 0 \- 10. 0 means print only critical errors about which you must be told. 1 means print all errors, even ones that are not overly important. 1+ means print more errors (if any) \-e 0 is good for cron jobs.
.br
Configuration Option: \fBerrorlevel\fP
.IP "\fB\-R [time in minutes]\fP" 
Sets the maximum amount of time yum will wait before performing a command \- it randomizes over the time.
.IP "\fB\-C\fP" 
Tells yum to run entirely from cache - does not download or update any
headers unless it has to to perform the requested action.
.IP "\fB\-\-version\fP" 
Reports the \fByum\fP version number and exits.
.IP "\fB\-\-showduplicates\fP" 
Doesn't limit packages to their latest versions in the info, list and search
commands (will also affect plugins which use the doPackageLists() API).
.IP "\fB\-\-installroot=root\fP" 
Specifies an alternative installroot, relative to which all packages will be
installed.
.br
Configuration Option: \fBinstallroot\fP
.IP "\fB\-\-enablerepo=repoidglob\fP"
Enables specific repositories by id or glob that have been disabled in the 
configuration file using the enabled=0 option.
.br
Configuration Option: \fBenabled\fP
.IP "\fB\-\-disablerepo=repoidglob\fP"
Disables specific repositories by id or glob. 
.br
Configuration Option: \fBenabled\fP
.IP "\fB\-\-obsoletes\fP"
This option only has affect for an update, it enables \fByum\fP\'s obsoletes
processing logic. For more information see the \fBupdate\fP command above.
.br
Configuration Option: \fBobsoletes\fP
.IP "\fB\-x, \-\-exclude=package\fP"
Exclude a specific package by name or glob from updates on all repositories.
Configuration Option: \fBexclude\fP
.br
.IP "\fB\-\-color=[always|auto|never]\fP"
Display colorized output automatically, depending on the output terminal,
always (using ANSI codes) or never.
Configuration Option: \fBcolor\fP
.br
.IP "\fB\-\-disableexcludes=[all|main|repoid]\fP"
Disable the excludes defined in your config files. Takes one of three options:
.br
all == disable all excludes
.br
main == disable excludes defined in [main] in yum.conf
.br
repoid == disable excludes defined for that repo
.br
.IP "\fB\-\-disableplugin=plugin\fP"
Run with one or more plugins disabled, the argument is a comma seperated list
of wildcards to match against plugin names.
.br
.IP "\fB\-\-noplugins\fP"
Run with all plugins disabled.
.br
Configuration Option: \fBplugins\fP
.IP "\fB\-\-nogpgcheck\fP"
Run with gpg signature checking disabled.
.br
Configuration Option: \fBgpgcheck\fP
.IP "\fB\-\-skip\-broken\fP"
Resolve depsolve problems by removing packages that are causing problems
from the transaction.
.br
Configuration Option: \fBskip_broken\fP
.PP 
.IP "\fB\-t, --tolerant\fP"
This option currently does nothing.
.br
.SH "LIST OPTIONS"
The following are the ways which you can invoke \fByum\fP in list
mode\&.  Note that all \fBlist\fP commands include information on the
version of the package\&.
.IP 
.IP "\fByum list [all | glob_exp1] [glob_exp2] [\&.\&.\&.]\fP"
List all available and installed packages\&.
.IP "\fByum list available [glob_exp1] [\&.\&.\&.]\fP"
List all packages in the yum repositories available to be installed\&.
.IP 
.IP "\fByum list updates [glob_exp1] [\&.\&.\&.]\fP"
List all packages with updates available in the yum repositories\&.
.IP 
.IP "\fByum list installed [glob_exp1] [\&.\&.\&.]\fP"
List the packages specified by \fIargs\fP\&.  If an argument does not
match the name of an available package, it is assumed to be a
shell\-style glob and any matches are printed\&.
.IP
.IP "\fByum list extras [glob_exp1] [\&.\&.\&.]\fP"
List the packages installed on the system that are not available in any yum
repository listed in the config file.
.IP
.IP "\fByum list obsoletes [glob_exp1] [\&.\&.\&.]\fP"
List the packages installed on the system that are obsoleted by packages
in any yum repository listed in the config file.
.IP
.IP "\fByum list recent\fP"
List packages recently added into the repositories. 
.IP
.IP "\fBSpecifying package names\fP"
All the list options mentioned above take file-glob-syntax wildcards or package
names as arguments, for example \fByum list available 'foo*'\fP will list
all available packages that match 'foo*'. (The single quotes will keep your
shell from expanding the globs.)
.IP
.PP 
.SH "CLEAN OPTIONS"
The following are the ways which you can invoke \fByum\fP in clean
mode. Note that "all files" in the commands below means 
"all files in currently enabled repositories". 
If you want to also clean any (temporarily) disabled repositories you need to
use \fB--enablerepo='*'\fP option.

.IP "\fByum clean packages\fP"
Eliminate any cached packages from the system.  Note that packages are not automatically deleted after they are downloaded.

.IP "\fByum clean headers\fP"
Eliminate all of the header files which yum uses for dependency resolution.

.IP "\fByum clean metadata\fP"
Eliminate all of the files which yum uses to determine the remote
availability of packages. Using this option will force yum to download all the 
metadata the next time it is run.

.IP "\fByum clean dbcache\fP"
Eliminate the sqlite cache used for faster access to metadata.
Using this option will force yum to recreate the cache the next time
it is run.

.IP "\fByum clean all\fP"
Runs \fByum clean packages\fP and \fByum clean headers\fP, \fByum clean metadata\fP and \fByum clean dbcache\fP as above.

.PP
.SH "MISC"
.IP "\fBSpecifying package names\fP"
A package can be referred to for install,update,list,remove etc with any 
of the following:
.IP
.br
\fBname\fP
.br
\fBname.arch\fP
.br
\fBname-ver\fP
.br
\fBname-ver-rel\fP
.br
\fBname-ver-rel.arch\fP
.br
\fBname-epoch:ver-rel.arch\fP
.br
\fBepoch:name-ver-rel.arch\fP
.IP
For example: \fByum remove kernel-2.4.1-10.i686\fP

.PP 
.SH "PLUGINS"
Yum can be extended through the use of plugins. A plugin is a Python ".py" file
which is installed in one of the directories specified by the \fBpluginpath\fP
option in yum.conf. For a plugin to work, the following conditions must be met:
.LP
1. The plugin module file must be installed in the plugin path as just
described.
.LP
2. The global \fBplugins\fP option in /etc/yum/yum.conf must be set to `1'.
.LP
3. A configuration file for the plugin must exist in
/etc/yum/pluginconf.d/<plugin_name>.conf and the \fBenabled\fR setting in this
file must set to `1'. The minimal content for such a configuration file is:
.IP
[main]
.br
enabled = 1
.LP
See the \fByum.conf(5)\fR man page for more information on plugin related
configuration options.

.PP
.SH "FILES"
.nf
/etc/yum/yum.conf
/etc/yum/repos.d/
/etc/yum/pluginconf.d/
/var/cache/yum/
.fi 

.PP
.SH "SEE ALSO"
.nf
.I pkcon (1)
.I yum.conf (5)
.I yum-updatesd (8)
.I package-cleanup (1)
.I repoquery (1)
.I yum-complete-transaction (1)
.I yumdownloader (1)
.I yum-utils (1)
http://linux.duke.edu/yum/
http://wiki.linux.duke.edu/YumFaq
yum search yum
.fi

.PP
.SH "AUTHORS"
.nf
See the Authors file included with this program.
.fi

.PP
.SH "BUGS"
There of course aren't any bugs, but if you find any, you should first
consult the Faq mentioned above and then email the mailing list:
yum@lists.linux.duke.edu or filed in bugzilla.
.fi
