#! /bin/bash

GITREV=${1:-$(git rev-parse --short HEAD)}
# shorten to 7 characters
GITREV=${GITREV:0:7}

echo $GITREV

TARGET_DIR=$HOME/rpmbuild/SOURCES
mkdir -p $TARGET_DIR
git archive ${GITREV} --prefix=dnf/ | xz > $TARGET_DIR/dnf-${GITREV}.tar.xz
